### ISSUE TITLE
use enums instead of returning bool

### ISSUE THREAD

**Issue by Be-ing** [uklotzde/discro#3]
I find the `on_changed` callbacks passed to `tasklet::capture_changes` difficult to read because I have to refer to the documentation to remember the meaning of the returned bool. It is easy to confuse whether true means continue or false means continue. Returning an enum with two states, perhaps called Continue and Abort, would help.

**Comment by Be-ing** [comment]
Another place this occurs is `Publisher::modify`. For example, [this function](https://gitlab.com/uklotzde/aoide-rs/-/blob/6bb858d6e7057442ab350be6138d5435e5fd6899/crates/desktop-app/src/track/repo_search/mod.rs#L95) is multiple layers removed from the call to `Publisher::modify`, making it cumbersome to find what the returned bool signifies.

**Comment by uklotzde** [comment]
I agree about the on_changed semantics, noticed that too.

For the modify() function I don't see an urgent need. It simply follows the Tokio semantics. After removing one of the boolean return values this might become less confusing.

**Comment by uklotzde** [comment]
Fixed in v0.7.0 (66bedc281c1383e989178e92eb423e270a8846b0).

I would like to defer the decision about modify until later.
